# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19U-bJJ8th8E49dQa2J9tu_l6qJ5q3qhU
"""

def aquarium():
    num_fish = int(input("How many fish do you want to add to the aquarium? "))
    print("Great, we'll add", num_fish, "fish to the aquarium!")
    water_type = input("What type of water does your aquarium use? ")
    print("Got it, your aquarium uses", water_type, "water.")
    
aquarium()

def school()
    type_fish = input("What type of fish will this school consist of? ")
    print("Wow! A school of", type_fish, "!")

school()
